### ISSUE TITLE
运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子

### ISSUE THREAD

**Issue by JionghaoSong** [ZZK23/data-science#1]

**Comment by ZZK23** [comment]
已给star

**Comment by JionghaoSong** [comment]
感谢




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Feb 14, 2023 02:21 PM
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
Subject:&nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)





 
已给star

**Comment by ZZK23** [comment]
打扰问下你的程序运行正常吗，我今天微信推送的少了很多内容，只有前面几行，后面的生日啥的都没了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月14日(星期二) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)





 感谢 
 
 
 
 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&amp;gt;; 
 Date:&amp;nbsp;Tue, Feb 14, 2023 02:21 PM 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 Subject:&amp;nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1) 
 
 
 
 
 
   
 已给star

**Comment by JionghaoSong** [comment]
收到反馈，我先简单看看原因是啥。
最近要毕业，问题大的话可能得月底🥺

---Original---
From: ***@***.***&gt;
Sent at: 2023年5月5日(Fri) PM4:55
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)




 打扰问下你的程序运行正常吗，我今天微信推送的少了很多内容，只有前面几行，后面的生日啥的都没了 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年2月14日(星期二) 下午2:22 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1) 
 
 
 
 
 
  感谢  
   
   
   
   
  ------------------&amp;amp;nbsp;Original&amp;amp;nbsp;------------------  
  From:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&amp;amp;gt;;  
  Date:&amp;amp;nbsp;Tue, Feb 14, 2023 02:21 PM  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  Subject:&amp;amp;nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)  
   
   
   
   
   
     
  已给star

**Comment by ZZK23** [comment]
好的，麻烦了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)





 收到反馈，我先简单看看原因是啥。 
 最近要毕业，问题大的话可能得月底🥺 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Sent at: 2023年5月5日(Fri) PM4:55 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 Subject: Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1) 
 
 
 
 
  打扰问下你的程序运行正常吗，我今天微信推送的少了很多内容，只有前面几行，后面的生日啥的都没了  
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年2月14日(星期二) 下午2:22  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)  
   
   
   
   
   
   感谢   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;Original&amp;amp;amp;nbsp;------------------   
   From:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   Date:&amp;amp;amp;nbsp;Tue, Feb 14, 2023 02:21 PM   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.***&amp;amp;amp;gt;;"State ***@***.***&amp;amp;amp;gt;;   
   Subject:&amp;amp;amp;nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)   
     
     
     
     
     
       
   已给star

**Comment by JionghaoSong** [comment]
微信改版了，不让自定义了。
具体看代码的issue



---Original---
From: ***@***.***&gt;
Sent at: 2023年5月5日(Fri) PM5:48
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)




 好的，麻烦了，谢谢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年5月5日(星期五) 下午5:39 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1) 
 
 
 
 
 
  收到反馈，我先简单看看原因是啥。  
  最近要毕业，问题大的话可能得月底🥺  
   
  ---Original---  
  From: ***@***.***&amp;amp;gt;  
  Sent at: 2023年5月5日(Fri) PM4:55  
  To: ***@***.***&amp;amp;gt;;  
  Cc: ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  Subject: Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)  
   
   
   
   
   打扰问下你的程序运行正常吗，我今天微信推送的少了很多内容，只有前面几行，后面的生日啥的都没了   
     
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2023年2月14日(星期二) 下午2:22   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)   
     
     
     
     
     
    感谢    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;Original&amp;amp;amp;amp;nbsp;------------------    
    From:                                                                                                                        "ZZK23/data-science"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    Date:&amp;amp;amp;amp;nbsp;Tue, Feb 14, 2023 02:21 PM    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.***&amp;amp;amp;amp;gt;;"State ***@***.***&amp;amp;amp;amp;gt;;    
    Subject:&amp;amp;amp;amp;nbsp;Re: [ZZK23/data-science] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)    
       
       
       
       
       
         
    已给star
